name: Node.js CI

on:
  push:
    branches: [ initial-dev ]
  pull_request:
    branches: [ initial-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18', 'lts/*', 'node']
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, lint , test and cover ${{ matrix.node-version }}
        run: |
          npm ci
          npm run lint
